DEVICE_PATH := device/samsung/a536b_ds

# Inherit the validated Exynos 1280 common baseline.
include device/samsung/s5e8825-common/BoardConfigCommon.mk

# Inherit device-specific proprietary flags when available.
include vendor/samsung/a536b_ds/BoardConfigVendor.mk

# Keep explicit A53/A536B identifiers.
TARGET_BOOTLOADER_BOARD_NAME := s5e8825
TARGET_SOC := s5e8825
TARGET_BOARD_PLATFORM := erd8825

# SM-A536B DTBO mapping.
BOARD_DTBO_CFG := $(DEVICE_PATH)/configs/kernel/a53x.cfg

# Kernel source and defconfig used by active public trees.
TARGET_KERNEL_SOURCE := kernel/samsung/s5e8825
TARGET_KERNEL_CONFIG := s5e8825-unified_defconfig
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_NO_GCC := true
TARGET_KERNEL_ADDITIONAL_FLAGS := TARGET_SOC=s5e8825 BRANCH=android12-5.10 KMI_GENERATION=9

# Partition geometry from recent stock-backed bring-up trees.
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_SUPER_PARTITION_SIZE := 11744051200
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 11739856896
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext vendor vendor_dlkm product odm

TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_ODM := odm

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_USES_METADATA_PARTITION := true

TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Security/release defaults.
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 0
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --algorithm NONE
VENDOR_SECURITY_PATCH := 2025-10-01

# Radio/OTA behavior.
AB_OTA_UPDATER := false
ENABLE_VENDOR_RIL_SERVICE := true
TARGET_OTA_ASSERT_DEVICE := a53x
